apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysql-root-pass
    literals:
    - password=redhat
  - name: mysql-user-pass
    literals:
    - password=redhat
    - username=mysql
  - name: mysql-db-url
    literals:
    - database=mysqld
resources:
  - mysql.yaml
  - nginx.yaml
